### ISSUE TITLE
Source for the wind status thresholds?

### ISSUE THREAD

**Issue by justinmanley** [open-city/kcbx-petcoke#2]
This app maintains two wind speed thresholds. Anything above the first threshold is considered a moderate health danger; anything above the second threshold is considered hazardous.

Where do these thresholds come from? Can you provide a link? It would be nice to be able to point folks receiving notifications to a page that explains why the wind speed thresholds are important and what they can do to protect their families when the wind reaches hazardous levels.

**Comment by benwilhelm** [comment]
http://www.midwestenergynews.com/2014/01/14/in-chicago-neighbors-say-petcoke-rules-full-of-loopholes/

You'll find the reference about halfway down in the section called "Too tough?"

**Comment by benwilhelm** [comment]
Also, see here:

http://www.cityofchicago.org/content/dam/city/depts/cdph/environmental_health_and_food/CityofChicagoResponsetoCommentsReceivedonBulkMaterialRules.pdf

Item 8 on page 9 talks about where the Department of Public Health gets the 15mph threshold.

**Comment by jwang207** [comment]
Call Mayer Rahm Emanuel at ######## and asdf@asdf to demand 0 Petcoke in your community

#Script to call (mayor) - (i.e. We are calling to demand 0 throughput of petcoke! The department of planning and development are deciding what amounts of petcoke can be in our community. The American Cancer Society, Harvard University and the EPA have determined that tiny particles that get in the air including Petcoke can lead to heart disease and lung disease at any time you are exposed. 

“Rahm Emanuel and John Pope said they would ‘regulate pet coke out of Chicago.’ Obviously, that strategy has failed. We need our elected officials to protect the people, not the polluters,” Bautista 

says.

Abstract

Exposure to volatile compounds can have longterm health risks, increase the risk of death, and cause property damage. KCBX maintains large stockpiles of petroleum coke, a volitile compound in the south side of Chicago. Longterm studies by Harvard University and the American Cancer Society have concluded that these particles increase the risk of heart disease and may increase the risk of lung cancer. Studies of the Petcoke in Chicago has also found that they contain heavy metals. Currently the city of Chicago recommends residents of the 10th ward stay indoors when winds are over 15 mile/hr. KCBX and local businesses have complained that the regulations are too stringent. We believe that these regulations are not stringent enough to prevent the health hazards that are posed to the citizens of the city of Chicago. 

Introduction

What is it?

Petcoke for short, petroleum coke is a byproduct of the refining process that extracts petroleum from "tar sands". The petroleum coke in Chicago's city limits is stored along the banks of the Calumet River on Chicago's Southeast Side, and arrive from BP refinery in Whiting, Indiana.

What is it for?

Petroleum coke is used to fuel power plants, cement kilns, and steel mills mainly in emerging economies like China, India, Mexico, and Turkey. 

What happens when you're exposed? Who is at risk?

When exposed for the first time, the immediate effects are similar to any other kind of dust - irritation of the eyes, nose and throat for most people. However those who have underlying diseases of the heart and lungs may have more severe reactions including irregular heart beats, which can be fatal. 

Reference: http://www.epa.gov/airquality/particulatematter/pdfs/pm-color.pdf

(Detailed Version below)
Long term exposure to particles smaller than 2.5 uM increases the risk of all type causes of death. Several longterm studies have shown that exposure to small particulate materials increases the risk of death from lung cancer and heart disease. The American Cancer Society found ischemic heart disease, a disease category including heart attacks, and commonly associated with tobacco smoke and obesity increased with exposure to particles as small as 2.5 uM, the size.(2) Furthermore the ACS found that exposure to small particles increased mortality by 7.5%, and that particles that had a high sulfur concentration, such as petroleum coke increased mortality risk by 12.5%. 

A long term study by Harvard University followed particulate matter levels over 35 years. The studies major findings were that every 10 uM/L exposure above 18 uM/L increased all cause mortality by 14%, mortality from heart disease by 26% and lung cancer mortality by 37%. The study also addressed sulfur co-exposure confounding the findings. They saw that the mortality risks remained constant despite drops in the level of sulfate in the particles between 14% to 54% depending on the city. This suggests that the role particles have in the development or exacerbation of chronic diseases to be relatively independent of the chemical makeup of the particles.(3)

Reference: 
1.http://www.cityofchicago.org/content/dam/city/depts/cdph/environmental_health_and_food/CityofChicagoResponsetoCommentsReceivedonBulkMaterialRules.pdf
2. http://www.ncbi.nlm.nih.gov/pubmed/22456598
3. Lepeule, Johanna et al. “Chronic Exposure to Fine Particles and Mortality: An Extended Follow-up of the Harvard Six Cities Study from 1974 to 2009.” Environmental Health Perspectives 120.7 (2012): 965–970. PMC. Web. 29 Apr. 2015.

http://www.aqmd.gov/docs/default-source/rule-book/reg-xi/rule-1158.pdf?sfvrsn=4

 tiny particulate matters up to 2.7 uM and wind speed. The graph shows that the particles tend to become most concentrated at 6.5 m/s -> 14.7 miles/hr. 

This is the article: http://senseable.mit.edu/papers/pdf/2008_Kumar_et_al_Science_of_the_Total_Environment.pdf

**Comment by jwang207** [comment]
Wind alert! The City of Chicago recommends you limit outdoor activities to reduce Pet Coke exposure. Text back “action” to take action.
